local containers = require("symfony.containers")
local assert = require("luassert")
local fixturesLoader = require("tests/fixtures/load")
local utils = require("symfony.utils")

describe("containers", function()
  before_each(function()
    containers.clear_storage()
  end)
  it("returns nil for missing container", function()
    local actual = containers.find_one_by_name("bad_name")
    assert.is_nil(actual)
  end)

  it("find by name", function()
    local fake_dump = fixturesLoader.containers()
    containers.update_storage(fake_dump)
    local actual = containers.find_one_by_name("argument_metadata_factory")
    assert.is_not_nil(actual)
  end)

  it("filter by name", function()
    local fake_dump = fixturesLoader.containers()
    containers.update_storage(fake_dump)
    local actual = containers.filter_by_name("resolver")
    local actual_count = vim.tbl_count(actual)
    assert.is_equal(actual_count, 3)

    local actual_empty = containers.filter_by_name("bad_name")
    local actual_empty_count = vim.tbl_count(actual_empty)
    assert.is_equal(actual_empty_count, 0)
  end)
end)
