local routers = require("symfony.routers")
local utils = require("symfony.utils")
local assert = require("luassert")
local fixturesLoader = require("tests/fixtures/load")

describe("routers", function()
  before_each(function()
    routers.clear_storage()
  end)

  it("FindByNameNotFound", function()
    local actual = routers.find_one_by_name("bad_name")
    assert.is_nil(actual)
  end)

  it("FindByNameFound", function()
    local fake_dump = fixturesLoader.routers()
    routers.update_storage(fake_dump)
    local actual = routers.find_one_by_name("home")
    assert.is_equal(actual["name"], "home")
  end)

  it("FilterByName", function()
    local fake_dump = fixturesLoader.routers()
    routers.update_storage(fake_dump)
    local actual = routers.filter_by_name("bad_name")
    local actual_count = vim.tbl_count(actual)
    assert.is_equal(actual_count, 0)

    local actual_admin = routers.filter_by_name("admin")
    local admin_count = vim.tbl_count(actual_admin)
    assert.is_equal(admin_count, 2)
  end)

  it("ResolvePathByNS", function()
    local path = routers.resolve_namespace_path("App\\Controller\\Site\\DefaultController")
    assert.is_equal(path, "src/Controller/Site/DefaultController.php")
  end)

  it("FindControllerPathFound", function()
    local fake_dump = fixturesLoader.routers()
    routers.update_storage(fake_dump)
    local actual = routers.get_controller_by_name("home")
    local expected = { "App\\Controller\\Site\\DefaultController", "index" }
    assert.are.same(actual, expected)
  end)

  it("FindControllerPathNotFound", function()
    local fake_dump = fixturesLoader.routers()
    routers.update_storage(fake_dump)
    local actual = routers.get_controller_by_name("bad_name")
    local expected = {}
    assert.are.same(actual, expected)
  end)
end)
